features:
  embed: true

security:
  cors:
    enabled: true
    origin:
      - http://localhost:8080
      - http://localhost:3000
  iframe:
    enabled: true
    origins:
      - http://localhost:8080