plugins {
    id 'java'
    id 'war'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

configurations {
    all {
        exclude group: 'javax', module: 'javaee-api'
        exclude group: 'javax', module: 'javax.faces-api'
        exclude group: 'javax', module: 'javax.servlet-api'
        exclude group: 'javax', module: 'javax.enterprise.api'
        exclude group: 'javax', module: 'javax.persistence-api'
        exclude group: 'javax', module: 'javax.annotation-api'
    }
}

dependencies {
    implementation 'org.primefaces:primefaces:13.0.0:jakarta'

    compileOnly 'jakarta.faces:jakarta.faces-api:4.0.1'
    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    compileOnly 'jakarta.enterprise:jakarta.enterprise.cdi-api:4.0.1'
    compileOnly 'jakarta.persistence:jakarta.persistence-api:3.1.0'

    implementation 'org.hibernate.orm:hibernate-core:6.2.7.Final'
}

war {
    archiveFileName = 'webapp.war'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from('src/main/webapp') {
        include '**/*.css'
        include '**/*.js'
        include '**/*.jpg'
        include '**/*.png'
        include '**/*.gif'
        include '**/*'
        into ''
    }

    exclude '**/javax/**'
    exclude '**/META-INF/versions/**'
    exclude '**/*.jar'

    from('src/main/resources') {
        include '**/*'
        into 'WEB-INF/classes'
    }
}

compileJava {
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-parameters']
}
